apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-db-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /flask-storage
    server: 192.168.122.84
